n=input("digite algo:")
print("Qual é a classe do que foi digitado?",type(n))
print("O que foi digitado é somente númerico?",n.isnumeric())
print("O que foi digitado é somente letras maiúsculas?",n.isupper())
print("O que foi digitado é somente letras minúsculas?",n.islower())
print("O que foi digitado é  letras?",n.isalpha())
print("O que foi digitado é alfanumérico",n.isalnum())
print("que foi digitado possui espaços?",n.isspace())
print("que foi digitado é um número de base 10?",n.isdecimal())
print("é capitalizado?",n.istitle())
